Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CEC.SRV.BLL;
using CEC.SRV.Domain;
using CEC.SRV.Domain.Lookup;
using CEC.Web.SRV.Infrastructure.Grids;
using CEC.Web.SRV.Models.History;
using Lib.Web.Mvc.JQuery.JqGrid;

namespace CEC.Web.SRV.Controllers
{
    public class HistoryController : BaseController
    {
        private readonly IAuditerBll _auditerBll;

        public HistoryController(IAuditerBll auditerBll)
        {
            _auditerBll = auditerBll;
        }

        public ActionResult ManagerTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListManagerTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<ManagerType>(pageRequest, id);

            return data.ToJqGridJsonResult<ManagerType, LookupHistoryGridModel>();
        }

        public ActionResult ConflictShareReasonHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListConflictShareReasonHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<ConflictShareReasonTypes>(pageRequest, id);

            return data.ToJqGridJsonResult<ConflictShareReasonTypes, LookupHistoryGridModel>();
        }


        public ActionResult GenderHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListGenderHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<Gender>(pageRequest, id);

            return data.ToJqGridJsonResult<Gender, LookupHistoryGridModel>();
        }

        public ActionResult ElectionTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListElectionTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<ElectionType>(pageRequest, id);

            return data.ToJqGridJsonResult<ElectionType, LookupHistoryGridModel>();
        }

        public ActionResult ElectionHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListElectionHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<ElectionHistoryGridModel>();

            var data = _auditerBll.Get<Election>(pageRequest, id);

            return data.ToJqGridJsonResult<Election, ElectionHistoryGridModel>();
        }

        public ActionResult StreetTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListStreetTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<StreetType>(pageRequest, id);

            return data.ToJqGridJsonResult<StreetType, LookupHistoryGridModel>();
        }

        public ActionResult PersonStatusHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListPersonStatusHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<PersonStatusHistoryGridModel>();

            var data = _auditerBll.Get<PersonStatusType>(pageRequest, id);

            return data.ToJqGridJsonResult<PersonStatusType, PersonStatusHistoryGridModel>();
        }

        public ActionResult DocumentTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListDocumentTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<DocumentTypeHistoryGridModel>();

            var data = _auditerBll.Get<DocumentType>(pageRequest, id);

            return data.ToJqGridJsonResult<DocumentType, DocumentTypeHistoryGridModel>();
        }

        public ActionResult RegionTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListRegionTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<RegionTypeHistoryGridModel>();

            var data = _auditerBll.Get<RegionType>(pageRequest, id);

            return data.ToJqGridJsonResult<RegionType, RegionTypeHistoryGridModel>();
        }

        public ActionResult RegionHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListRegionHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<RegionHistoryGridModel>();

            var data = _auditerBll.Get<Region>(pageRequest, id);

            return data.ToJqGridJsonResult<Region, RegionHistoryGridModel>();
        }

        public ActionResult StreetHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListStreetHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<StreetsHistoryGridModel>();

            var data = _auditerBll.Get<Street>(pageRequest, id);

            return data.ToJqGridJsonResult<Street, StreetsHistoryGridModel>();
        }

        public ActionResult PollingStationHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListPollingStationHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<PollingStationHistoryGridModel>();

            var data = _auditerBll.Get<PollingStation>(pageRequest, id);

            return data.ToJqGridJsonResult<PollingStation, PollingStationHistoryGridModel>();
        }

        public ActionResult AddressHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListAddressHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<AddressHistoryGridModel>();

            var data = _auditerBll.Get<Address>(pageRequest, id);

            return data.ToJqGridJsonResult<Address, AddressHistoryGridModel>();
        }

        public ActionResult PersonAddressTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListPersonAddressTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<PersonAddressType>(pageRequest, id);

            return data.ToJqGridJsonResult<PersonAddressType, LookupHistoryGridModel>();
        }

        public ActionResult ConfigurationSettingHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListConfigurationSettingHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<ConfigurationSettingHistoryGridModel>();

            var data = _auditerBll.Get<ConfigurationSetting>(pageRequest, id);

            return data.ToJqGridJsonResult<ConfigurationSetting, ConfigurationSettingHistoryGridModel>();
        }
    }
}

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Controllers/VotersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using Amdaris.Domain.Paging;
using AutoMapper;
using CEC.SRV.BLL;
using CEC.SRV.BLL.Dto;
using CEC.SRV.BLL.Extensions;
using CEC.SRV.Domain;
using CEC.SRV.Domain.Lookup;
using CEC.Web.SRV.Infrastructure;
using CEC.Web.SRV.Infrastructure.Export;
using CEC.Web.SRV.Infrastructure.Grids;
using System.Web.Mvc;
using CEC.SRV.Domain.Constants;
using CEC.Web.SRV.Infrastructure.Logger;
using CEC.Web.SRV.LoggingService;
using CEC.Web.SRV.Models.Voters;
using CEC.Web.SRV.Properties;
using CEC.Web.SRV.Resources;
using Lib.Web.Mvc.JQuery.JqGrid;
using RSP.CEC.WebClient.RspCecService;
using SoftTehnica.MvcReportViewer;
using CEC.SRV.Domain.ViewItem;
using CEC.Web.SRV.Models.Address;
using CEC.Web.SRV.Models.Conflict;
using CEC.SRV.Domain.Importer;
using UpdateAddressModel = CEC.Web.SRV.Models.Voters.UpdateAddressModel;

namespace CEC.Web.SRV.Controllers
{
    public class VotersController : BaseController
    {
        private readonly IConfigurationSettingBll _settingsBll;
        private readonly IVotersBll _bll;
        private readonly IPrintBll _printBll;
        private readonly IConflictBll _conflictBll;
        private string _rspUserName;
        private string _rspUserPwd;
        private const string RspUserParamName = "RspUser";
        private const string RspUserPwdParamName = "RspPass";

        public VotersController(IConfigurationSettingBll settingsBll, IVotersBll bll, IPrintBll printBll, IConflictBll conflictBll)
        {
            _settingsBll = settingsBll;
            _bll = bll;
            _printBll = printBll;
            _conflictBll = conflictBll;
        }

        // GET: /Voters/
        [Authorize(Roles = Transactions.Voters)]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StayStatements()
        {
            return View();
        }

        public JqGridJsonResult ListVotersAjax(JqGridRequest request, long? regionId, long? pollingStationId)
        {
            var pageRequest = request.ToPageRequest<VotersGridModel>();

            var data = _bll.GetByFilters(pageRequest, regionId, pollingStationId);

            return data.ToJqGridJsonResult<VoterViewItem, VotersGridModel>();
        }

        public JqGridJsonResult ListVotersAjax2(JqGridRequest request, long? regionId, long? pollingStationId,
            long? localityId = null,
            long? streetId = null,
            long? addressId = null,
            int? houseNumber = null,
            int? apNumber = null,
            string apSuffix = null
            )
        {
            var pageRequest = request.ToPageRequest<VotersGridModel>();

            var data = _bll.GetByFilters(pageRequest, regionId, pollingStationId,
                localityId,
                streetId,
                addressId,
                houseNumber,
                apNumber,
                apSuffix
            );

            return data.ToJqGridJsonResult<VoterViewItem, VotersGridModel>();
        }

        [HttpPost]
        public ActionResult ExportVoters(JqGridRequest request, ExportType exportType, long? regionId, long? pollingStationId)
        {
            return ExportGridData(request, exportType, "Alegatori", typeof(VotersGridModel),
                x => ListVotersAjax(x, regionId, pollingStationId));
        }

        public ActionResult SelectVoterStatus()
        {
            var voterStatus = _bll.GetAll<PersonStatusType>();

            return PartialView("_Select", voterStatus.ToSelectListUnencrypted(0, false, null, x => x.Name, x => x.Id));
        }

        public ActionResult SelectVoterGender()
        {
            var voterGender = _bll.GetAll<Gender>();

            return PartialView("_Select", voterGender.ToSelectListUnencrypted(0, false, null, x => x.Name, x => x.Name));
        }

        public ActionResult SearchVotersByIdnpAjax(JqGridRequest request, string idnp)
        {
            var pageRequest = request.ToPageRequest<SearchVotersGridModel>();

            var data = _bll.GetIdnp(pageRequest, idnp);

            return data.ToJqGridJsonResult<Person, SearchVotersGridModel>();
        }

        public JqGridJsonResult ListStayStatementsAjax(JqGridRequest request)
        {
            var pageRequest = request.ToPageRequest<StayStatementsGridModel>();

            var data = _bll.GetStayStatements(pageRequest);

            return data.ToJqGridJsonResult<StayStatement, StayStatementsGridModel>();
        }

        [HttpPost]
        public ActionResult ExportStayStatements(JqGridRequest request, ExportType exportType)
        {
            return ExportGridData(request, exportType, "DeclaratiiSedere",
                typeof(StayStatementsGridModel), ListStayStatementsAjax);
        }

        public ActionResult ListVoterAdressesHistoryAjax(JqGridRequest request, long personId)
        {
            var pageRequest = request.ToPageRequest<PersonFullAdressGridModel>();

            var data = _bll.GetAddressHistory(pageRequest, personId);

            return data.ToJqGridJsonResult<PersonAddress, PersonFullAdressGridModel>();
        }

        public ActionResult ListVoterConflictsHistoryAjax(JqGridRequest request, string personId)
        {
            var pageRequest = request.ToPageRequest<VoterConflictGridModel>();

            var data = _conflictBll.GetConflictHistory(pageRequest, personId);

            return data.ToJqGridJsonResult<RspModificationData, VoterConflictGridModel>();
        }

        public ActionResult ListVoterDocumentHistoryAjax(JqGridRequest request, long personId)
        {
            var pageRequest = request.ToPageRequest<VoterDocumentGridModel>();

            var data = _bll.GetIdentityDocumentsHistory(personId);

            return data.ToJqGridJsonResult<PersonDocument, VoterDocumentGridModel>();
        }

        public ActionResult ListVoterVotingStationHistoryAjax(JqGridRequest request, long personId)
        {
            var pageRequest = request.ToPageRequest<VoterPollingStationHistoryGridModel>();

            var data = _bll.GetPollingStationHistory(pageRequest, personId);

            return data.ToJqGridJsonResult<PollingStation, VoterPollingStationHistoryGridModel>();
        }

        public ActionResult CreateVoterProfile(long? personId, string idnp)
        {
            var person = personId.HasValue ? _bll.Get<Person>(personId.Value) : !string.IsNullOrEmpty(idnp) ? _bll.GetByIdnp(idnp) : null;
            if (person == null)
            {
                return PartialView("_VoterNotFound");
            }

            var personInfo = new VoterProfileModel
            {
                PersonId = person.Id,
                IDNP = person.Idnp,
                FirstName = person.FirstName,
                MiddleName = person.MiddleName,
                SurName = person.Surname,
                Age = "" + person.Age,
                Sex = person.Gender.Name,
                Status = person.CurrentStatus.StatusType.Name,
                DateOfBirth = person.DateOfBirth,

                Modified = person.Modified.HasValue ? person.Modified.Value.DateTime.ToString("dd.MM.yyyy") : string.Empty,
                ModifiedBy = person.ModifiedBy != null ? person.ModifiedBy.UserName : string.Empty
            };

            if (person.Document != null)
            {
                personInfo.DocType = person.Document.Type.Description;
                personInfo.DocNumber = person.Document.DocumentNumber;
                personInfo.DocIssuedDate = person.Document.IssuedDate;
                personInfo.DocIssuedBy = person.Document.IssuedBy;
                personInfo.DocValidBy = person.Document.ValidBy;
            }

            var model = new ViewVoterProfileModel
            {
                PersonInfo = personInfo,
                BaseAddressInfo = new VoterAdressModel
                {
                    PersonAddressId = person.EligibleAddress.Id,
                    AddressId = person.EligibleAddress.Address.Id,
                    ApNumber = person.EligibleAddress.ApNumber,
                    ApSuffix = person.EligibleAddress.ApSuffix,
                    BlNumber = person.EligibleAddress.Address.GetBuildingNumber(),
                    FullAddress = person.EligibleAddress.GetFullPersonAddress(true),
                    Street = person.EligibleAddress.Address.Street?.Name,
                    StreetId = person.EligibleAddress.Address.Street?.Id,
                    Region = person.EligibleAddress.Address.Street?.Region.Parent?.Name,
                    RegionId = person.EligibleAddress.Address.Street?.Region.Parent?.Id,
                    Locality = person.EligibleAddress.Address.Street?.Region.GetFullName(),
                    LocalityId = person.EligibleAddress.Address.Street?.Region.Id
                },

                RegionStreetsType = _bll.GetRegionStreetsType(),
                DeclaredStayAddressInfo = new PersonAddressModel(),
                ElectionInfo = new ElectionModel()
            };


            //SetViewData(model);
            return PartialView(model);
        }

        public ActionResult VotersBySurname(long? personId, string idnp)
        {
            var person = personId.HasValue ? _bll.Get<Person>(personId.Value) : !string.IsNullOrEmpty(idnp) ? _bll.GetByIdnp(idnp) : null;
            if (person == null)
            {
                return PartialView("_VoterNotFound");
            }

            var model = new VotersBySurnameModel()
            {
                PersonId = person.Id,
                IDNP = person.Idnp,
                FirstName = person.FirstName,
                MiddleName = person.MiddleName,
                SurName = person.Surname,
                BaseAdress = new VoterAdressModel
                {
                    PersonAddressId = person.EligibleAddress.Id,

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Views/Conflict/_AddressIdenticalList.cshtml
@using CEC.Web.SRV.Infrastructure.Grids
@using CEC.Web.SRV.Models.Conflict
@using Lib.Web.Mvc.JQuery.JqGrid
@model long?

@{
    var grid = Html.GridOptions<ConflictGridModel>("identicalAddressConflicts", width: 860)
        .SetOptions(x =>
        {
            x.LoadComplete = "$.identicalByAddressGrid.OnLoadComplete";
            x.OnSelectRow = "$.identicalByAddressGrid.OnRowSelect";
            x.MultiSelect = true;
            x.OnSelectAll = "$.identicalByAddressGrid.OnSelectAll";
         })
        .BuildGrid(Url.Action("ListIdenticalAddressesAjax", new { conflictId = Model }))
        .Navigator(new JqGridNavigatorOptions()
        {
            Add = false, Edit = false, Delete = false, CloneToTop = true
        });
}
<div class="col-sm-12">
    @grid.GetHtml()
</div>

<script type="text/javascript">
    $(document).ready(function() {
        @grid.GetJavaScript();
        $.forEachGrid($.removeClonedGridButtons);
    });
</script>

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Views/Conflict/_AddressRSVList.cshtml
@using CEC.Web.SRV.Infrastructure.Grids
@using CEC.Web.SRV.Models.Conflict
@using CEC.Web.SRV.Resources
@using Lib.Web.Mvc.JQuery.JqGrid
@model long?

@{
    var grid = Html.GridOptions<AddressRSVGridModel>("rsvAddresses", width: 860, rowsPerPage: 100)
        .SetOptions(x =>
        {
            x.ColumnsRemaping = new List<int> { 3, 4, 5, 1, 2, 0, 6, 7, 8, 9 };
        })
        .BuildGrid(Url.Action("ListAddressesAjax", new { regionId = Model }),
            deleteAction: null,
            addAction: null,
            editAction: null,
            unDeleteAction: Url.Action("UnDeleteAddress", "Address"),
            historyAction: Url.Action("AddressHistory", "History")
        )
        .Navigator(new JqGridNavigatorOptions()
        {
            Add = true,
            Edit = true,
            Delete = true,
            CloneToTop = true,
            AddFunction = "$.CreateUpdateAddressShortCut",
            EditFunction = "$.CreateUpdateAddressShortCut",
            DeleteFunction = "$.DeleteAddressShortCut"
        });
}
<div class="col-sm-12">
    @grid.GetHtml()
</div>

<script type="text/javascript">
    (function($) {

        var currentRegionId = null;;

        $.GetGridSelectedRegionId = function() {
            var selections = $("#rsvAddresses").jqGrid('getGridParam', 'selrow');
            var real = $("tr[id='" + selections + "'] > td[aria-describedby='rsvAddresses_RegionId']").attr('title');
            return real;
        }

        $.CreateUpdateAddressShortCut = function (addressId) {
            var url = '@Url.Action("SaveBuildingAddress", "Address")';

            var addressParam = '';
            var dialogTitle = '@MUI.AddressBuildingAdd_DialogTitle';
            if (addressId != undefined) {
                addressParam = '&addressId=' + addressId;
                dialogTitle = '@MUI.AddressBuildingEdit_DialogTitle';
                currentRegionId = $.GetGridSelectedRegionId();
            } else {
                currentRegionId = 0 + '@Model';
            }

            if (currentRegionId && currentRegionId  <= 0) {
                BootstrapDialog.alert({ message: 'Nu se poate adauga adresa in alta localitate decat localitatea conflictului', title: '@MUI.DialogTitle_Information' });
                return;
            }

            $.openDialog($(this), {
                url: url + '?regionId=' + currentRegionId + addressParam,
                title: dialogTitle,
                onSubmit: function () {
                    $("#rsvAddresses").trigger('reloadGrid');
                }
            });
        };

        $.DeleteAddressShortCut = function (addressId) {

            var url = '@Url.Action("DeleteAddress","Address")';

            BootstrapDialog.confirm('@MUI.AddressBuildingDelete_Message', function (result) {
                if (result) {
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: { addressId: addressId },
                        success: function (returnData) {
                            $("#rsvAddresses").trigger('reloadGrid');
                        }
                    });
                }

            });

        };

        $.getRegionId = function () {
            return { regionId: currentRegionId };
        };


    })(jQuery);

    $(document).ready(function () {
        @grid.GetJavaScript();
        $.forEachGrid($.removeClonedGridButtons);
    });
</script>

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Views/Conflict/_LocalityConflictList.cshtml
@using CEC.Web.SRV.Infrastructure.Grids
@using CEC.Web.SRV.Models.Conflict
@using Lib.Web.Mvc.JQuery.JqGrid
@using CEC.Web.SRV.Resources


@{
    var grid = Html.GridOptions<ConflictGridModel>("localityConflicts", rowsPerPage: 100, height: 310)
        .SetOptions(x =>
        {
            x.OnCellSelect = "onCellSelect";
            x.ColumnsModels.ApplyCustomVisibilityRules(new ConflictGridModelCustomVisibilityRules());
            x.PostDataScript = "{ 'gridType':function(){ return $('#region-dropdown').val()} }";
        })
        .BuildGrid(Url.Action("LocalityConflictAjax", "Conflict"))
        .Navigator(new JqGridNavigatorOptions() { Add = false, Edit = false, Delete = false, CloneToTop = true })
         .AddNavigatorButton(new JqGridNavigatorButtonOptions { Icon = "ui-icon-link", Caption = "Partajare Conflict", Id = "locality_shareConflict" })
         .AddNavigatorButton(new JqGridNavigatorButtonOptions { Icon = "ui-icon-newwin", Caption = MUI.Voters_VoterProfile, OnClick = "$.voterProfile", Id = "voterProfile" })
         .AddNavigatorButton(new JqGridNavigatorButtonOptions { Icon = "ui-icon-newwin", Caption = MUI.Voters_WithSame_SurnName, OnClick = "$.votersBySurname", Id = "votersBySurname" });
}

@grid.GetHtml()

<script type="text/javascript">
	$(document).ready(function () {
	    @grid.GetJavaScript();
	});

    //Show Share Conflict Modal
    $.shareConflict = function (e) {

        var selectedConflictModifiedDataId = GetGridSelectedConflictModifiedDataID();
        var selectedConflictDataId = GetGridSelectedConflictDataId();

        var url = '@Url.Action("ShareConflictView")';


        if (selectedConflictModifiedDataId == null || selectedConflictModifiedDataId == 0) {
            BootstrapDialog.alert({ message: '@MUI.VoterNotSelectedAlertMessage', title: '@MUI.DialogTitle_Information' });
            return;
        }


        url =  url + '?conflictModifiedDataId=' + selectedConflictModifiedDataId;
        url = url + '&conflictDataId=' + selectedConflictDataId;

        $.openDialog($(this), {
            title: '@MUI.ShareConflict_ModalTitle',
            usePost: true,
            url: url,
            onBeforeSerialize: function (submitForm) {
                var selectOptions = $('#AllocatedRegions')[0].options;
                for (var i = 0; i < selectOptions.length; i++) {
                    submitForm.append($('<input type="hidden" />').attr('name', 'AllocatedRegions[' + i + '].Value').val(selectOptions[i].value));
                    submitForm.append($('<input type="hidden" />').attr('name', 'AllocatedRegions[' + i + '].Text').val(selectOptions[i].text));
                }
            },
            onSubmit: function () {
                $("#localityConflicts").trigger('reloadGrid', [{ current: true }]);
                $.getCountNotification();
            }
        });
    }

    $.voterProfile = function (e) {
        var selectedIdnp = GetGridSelectedConflictIdnp();

        if (selectedIdnp == null || selectedIdnp == 0) {
            BootstrapDialog.alert({ message: '@MUI.VoterNotSelectedAlertMessage', title: '@MUI.DialogTitle_Information' });
            return;
        }

        $.openDialog($(this), {
            title: '@MUI.Voters_VoterProfile',
            url: '@Url.Action("CreateVoterProfile", "Voters")',
            usePost: true,
            postData: {
                idnp: selectedIdnp
            },
            onClose: function () {
                //dialog.close();
                //$.getCountNotification();
            }
        });
    }

    $.votersBySurname = function (e) {
        var selectedIdnp = GetGridSelectedConflictIdnp();

        if (selectedIdnp == null || selectedIdnp == 0) {
            BootstrapDialog.alert({ message: '@MUI.VoterNotSelectedAlertMessage', title: '@MUI.DialogTitle_Information' });
            return;
        }

        $.openDialog($(this), {
            title: '@MUI.Voters_WithSame_SurnName',
            url: '@Url.Action("VotersBySurname", "Voters")',
            usePost: true,
            postData: {
                idnp: selectedIdnp
            },
            onClose: function () {
                //dialog.close();
                //$.getCountNotification();
            }
        });
    }

    function GetGridSelectedConflictIdnp() {

        var selections = $("#localityConflicts").jqGrid('getGridParam', 'selrow');
        var real = $("tr[id='" + selections + "'] > td[aria-describedby='localityConflicts_Idnp']").attr('title');

        return real;
    }

    function GetGridSelectedConflictModifiedDataID() {
        var selections = $("#localityConflicts").jqGrid('getGridParam', 'selrow');
        var real = $("tr[id='" + selections + "'] > td[aria-describedby='localityConflicts_RspModificationDataId']").attr('title');

        return real;
    }

    function GetGridSelectedConflictDataId() {
        var selections = $("#localityConflicts").jqGrid('getGridParam', 'selrow');
        return selections;
    }

    //********


</script>

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Views/Conflict/_PollingStationList.cshtml
@model CEC.Web.SRV.Models.Conflict.PollingStationListModel

<div class="allAddress">
    @Html.EditorFor(x => x.PollingStationId) 
</div>

<script type="text/javascript">
    $('.allAddress .rsa-form-group > div.col-sm-2').removeClass('col-sm-2').addClass('col-sm-3');
</script>