Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Models/AppConfiguration/ConfigurationSettingsGridModel.cs
using System.ComponentModel.DataAnnotations;
using CEC.Web.SRV.Models.Grid;
using CEC.Web.SRV.Resources;
using Lib.Web.Mvc.JQuery.JqGrid;
using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;

namespace CEC.Web.SRV.Models.AppConfiguration
{
    public class ConfigurationSettingsGridModel : JqGridSoft
    {
        [JqGridColumnEditable(true)]
        [JqGridColumnSortable(true)]
        [JqGridColumnSearchable(true, SearchOperators = JqGridSearchOperators.TextOperators)]
        [Display(Name = "ConfigurationSetting_Name", ResourceType = typeof(MUI))]
        public string Name { get; set; }

        [JqGridColumnEditable(true)]
        [JqGridColumnSortable(true)]
        [JqGridColumnSearchable(true, SearchOperators = JqGridSearchOperators.TextOperators)]
        [Display(Name = "ConfigurationSetting_Value", ResourceType = typeof(MUI))]
        public string Value { get; set; }

        [JqGridColumnEditable(true)]
        [JqGridColumnSortable(true)]
        [JqGridColumnSearchable(true, SearchOperators = JqGridSearchOperators.TextOperators)]
        [Display(Name = "ConfigurationSetting_ApplicationName", ResourceType = typeof(MUI))]
        public string ApplicationName { get; set; }

    }
}

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Models/AppConfiguration/UpdateConfigurationSettingModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CEC.Web.SRV.Infrastructure;
using CEC.Web.SRV.Resources;

namespace CEC.Web.SRV.Models.AppConfiguration
{
    public class UpdateConfigurationSettingModel
    {
        public long Id { get; set; }

        [Display(Name = "ConfigurationSetting_Name", ResourceType = typeof(MUI))]
        public string Name { get; set; }

        [Display(Name = "ConfigurationSetting_Value", ResourceType = typeof(MUI))]
        public string Value { get; set; }

        [Display(Name = "ConfigurationSetting_ApplicationName", ResourceType = typeof(MUI))]
        public string ApplicationName { get; set; }
    }
}

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Controllers/AppConfigurationController.cs
using System;
using System.Web.Mvc;
using CEC.SRV.BLL;
using CEC.SRV.Domain;
using CEC.SRV.Domain.Constants;
using CEC.Web.SRV.Infrastructure;
using CEC.Web.SRV.Infrastructure.Export;
using CEC.Web.SRV.Infrastructure.Grids;
using CEC.Web.SRV.Models.AppConfiguration;
using CEC.Web.SRV.Resources;
using Lib.Web.Mvc.JQuery.JqGrid;

namespace CEC.Web.SRV.Controllers
{
	[Authorize(Roles = Transactions.AppConfiguration)]
	public class AppConfigurationController : BaseController
    {
        private readonly IConfigurationSettingBll _bll;

        public AppConfigurationController(IConfigurationSettingBll bll)
        {
            _bll = bll;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = Transactions.AppConfiguration)]
		public ActionResult CreateUpdateConfigurationSetting(long id)
        {
            var model = new UpdateConfigurationSettingModel();
            if (id != 0)
            {
                var configurationSetting = _bll.Get<ConfigurationSetting>(id);
                model.Id = configurationSetting.Id;
                model.Name = configurationSetting.Name;
                model.Value = configurationSetting.Value;
                model.ApplicationName = configurationSetting.ApplicationName;
            }
            return PartialView("_CreateUpdateConfigurationSetting", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUpdateConfigurationSetting(UpdateConfigurationSettingModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_CreateUpdateConfigurationSetting", model);
            }
            if (model.Id == 0)
            {
                ModelState.AddModelError("", MUI.ActionNotSupported);
                return PartialView("_CreateUpdateConfigurationSetting", model);
            }
            
            _bll.UpdateValue(model.Id, model.Value);
            return Content(Const.CloseWindowContent);
        }

        public JqGridJsonResult ListConfigurationSettingsAjax(JqGridRequest request)
        {
            var pageRequest = request.ToPageRequest<ConfigurationSettingsGridModel>();

            var data = _bll.Get<ConfigurationSetting>(pageRequest);

            return data.ToJqGridJsonResult<ConfigurationSetting, ConfigurationSettingsGridModel>();
        }
        
        [HttpPost]
        public void DeleteConfigurationSetting(long configSettingId)
        {
            _bll.Delete<ConfigurationSetting>(configSettingId);
        }

        [HttpPost]
        public void UnDeleteConfigurationSetting(long id)
        {
            _bll.UnDelete<ConfigurationSetting>(id);
        }

        [HttpPost]
        public ActionResult ExportConfigurationSettings(JqGridRequest request, ExportType exportType)
        {
            return ExportGridData(request, exportType, "ConfigurationSettings", typeof(ConfigurationSettingsGridModel), ListConfigurationSettingsAjax);
        }

        public ActionResult GetConfigurationSettingById(long configSettingId)
        {
            var configurationSetting = _bll.Get<ConfigurationSetting>(configSettingId);
            return Json(new {configurationSetting.Name,configurationSetting.Value,configurationSetting.ApplicationName}, JsonRequestBehavior.AllowGet);
        }

    }
}

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CEC.SRV.BLL;
using CEC.SRV.Domain;
using CEC.SRV.Domain.Lookup;
using CEC.Web.SRV.Infrastructure.Grids;
using CEC.Web.SRV.Models.History;
using Lib.Web.Mvc.JQuery.JqGrid;

namespace CEC.Web.SRV.Controllers
{
    public class HistoryController : BaseController
    {
        private readonly IAuditerBll _auditerBll;

        public HistoryController(IAuditerBll auditerBll)
        {
            _auditerBll = auditerBll;
        }

        public ActionResult ManagerTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListManagerTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<ManagerType>(pageRequest, id);

            return data.ToJqGridJsonResult<ManagerType, LookupHistoryGridModel>();
        }

        public ActionResult ConflictShareReasonHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListConflictShareReasonHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<ConflictShareReasonTypes>(pageRequest, id);

            return data.ToJqGridJsonResult<ConflictShareReasonTypes, LookupHistoryGridModel>();
        }


        public ActionResult GenderHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListGenderHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<Gender>(pageRequest, id);

            return data.ToJqGridJsonResult<Gender, LookupHistoryGridModel>();
        }

        public ActionResult ElectionTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListElectionTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<ElectionType>(pageRequest, id);

            return data.ToJqGridJsonResult<ElectionType, LookupHistoryGridModel>();
        }

        public ActionResult ElectionHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListElectionHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<ElectionHistoryGridModel>();

            var data = _auditerBll.Get<Election>(pageRequest, id);

            return data.ToJqGridJsonResult<Election, ElectionHistoryGridModel>();
        }

        public ActionResult StreetTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListStreetTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<StreetType>(pageRequest, id);

            return data.ToJqGridJsonResult<StreetType, LookupHistoryGridModel>();
        }

        public ActionResult PersonStatusHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListPersonStatusHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<PersonStatusHistoryGridModel>();

            var data = _auditerBll.Get<PersonStatusType>(pageRequest, id);

            return data.ToJqGridJsonResult<PersonStatusType, PersonStatusHistoryGridModel>();
        }

        public ActionResult DocumentTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListDocumentTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<DocumentTypeHistoryGridModel>();

            var data = _auditerBll.Get<DocumentType>(pageRequest, id);

            return data.ToJqGridJsonResult<DocumentType, DocumentTypeHistoryGridModel>();
        }

        public ActionResult RegionTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListRegionTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<RegionTypeHistoryGridModel>();

            var data = _auditerBll.Get<RegionType>(pageRequest, id);

            return data.ToJqGridJsonResult<RegionType, RegionTypeHistoryGridModel>();
        }

        public ActionResult RegionHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListRegionHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<RegionHistoryGridModel>();

            var data = _auditerBll.Get<Region>(pageRequest, id);

            return data.ToJqGridJsonResult<Region, RegionHistoryGridModel>();
        }

        public ActionResult StreetHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListStreetHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<StreetsHistoryGridModel>();

            var data = _auditerBll.Get<Street>(pageRequest, id);

            return data.ToJqGridJsonResult<Street, StreetsHistoryGridModel>();
        }

        public ActionResult PollingStationHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListPollingStationHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<PollingStationHistoryGridModel>();

            var data = _auditerBll.Get<PollingStation>(pageRequest, id);

            return data.ToJqGridJsonResult<PollingStation, PollingStationHistoryGridModel>();
        }

        public ActionResult AddressHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListAddressHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<AddressHistoryGridModel>();

            var data = _auditerBll.Get<Address>(pageRequest, id);

            return data.ToJqGridJsonResult<Address, AddressHistoryGridModel>();
        }

        public ActionResult PersonAddressTypeHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListPersonAddressTypeHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<LookupHistoryGridModel>();

            var data = _auditerBll.Get<PersonAddressType>(pageRequest, id);

            return data.ToJqGridJsonResult<PersonAddressType, LookupHistoryGridModel>();
        }

        public ActionResult ConfigurationSettingHistory(long id)
        {
            return PartialView(id);
        }

        [HttpPost]
        public JqGridJsonResult ListConfigurationSettingHistoryAjax(JqGridRequest request, long id)
        {
            var pageRequest = request.ToPageRequest<ConfigurationSettingHistoryGridModel>();

            var data = _auditerBll.Get<ConfigurationSetting>(pageRequest, id);

            return data.ToJqGridJsonResult<ConfigurationSetting, ConfigurationSettingHistoryGridModel>();
        }
    }
}

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Views/AppConfiguration/Index.cshtml
@using CEC.Web.SRV.Infrastructure.Grids
@using CEC.Web.SRV.Models.AppConfiguration
@using CEC.Web.SRV.Models.Lookup
@using CEC.Web.SRV.Resources
@using Lib.Web.Mvc.JQuery.JqGrid

@{
    ViewBag.Title = MUI.Configurationsettings_TabTitle;
}

@{
	var grid = Html.GridOptions<ConfigurationSettingsGridModel>("configSettings")
        .BuildGrid(Url.Action("ListConfigurationSettingsAjax"), null, null, null, null,
            Url.Action("ConfigurationSettingHistory", "History"), Url.Action("ExportConfigurationSettings"))
		.Navigator(new JqGridNavigatorOptions()
		{
			Add = false,
			Edit = true,
			Delete = false,
			Search = true,
            EditFunction = "$.CreateUpdateConfigurationSetting",
            DeleteFunction = "$.DeleteConfigurationSetting",
            CloneToTop = true
		});
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-content">
                <h4 class="page-header">@MUI.Configurationsettings_TabTitle</h4>
                @grid.GetHtml()
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function ($) {
        $(document).ready(function () {
            @grid.GetJavaScript();
        });
        
        $.CreateUpdateConfigurationSetting = function (configSettingId) {
            var url = '@Url.Action("CreateUpdateConfigurationSetting","AppConfiguration")';
            var dialogTitle = '@MUI.ConfigurationSettingAdd_DialogTitle';
            if (configSettingId != undefined) {
                dialogTitle = '@MUI.ConfigurationSettingEdit_DialogTitle';
            } else {
                configSettingId = 0;
            }
            
            $.openDialog($(this), {
                url: url + '?id=' + configSettingId,
                title: dialogTitle,
                onSubmit: function () {
                    $('#configSettings').trigger('reloadGrid');
                }
            });
            
           
        };

        $.DeleteConfigurationSetting = function (configSettingId) {
            var url = '@Url.Action("DeleteConfigurationSetting","AppConfiguration")';

            BootstrapDialog.confirm('@MUI.PollingStationDelete_Message', function (result) {
                if (result) {
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: { configSettingId: configSettingId },
                        success: function () {
                            $('#configSettings').trigger('reloadGrid');
                        }
                    });
                }

            });

        };
    })(jQuery);
</script>

Downloads/cec.srv_indrivo-dev/src/CEC.Web.SRV/Views/AppConfiguration/_CreateUpdateConfigurationSetting.cshtml
@using CEC.SRV.BLL
@using CEC.SRV.Domain
@using CEC.Web.SRV.Resources
@model CEC.Web.SRV.Models.AppConfiguration.UpdateConfigurationSettingModel

<div class="clearfix">

    @using (Html.BeginForm("CreateUpdateConfigurationSetting", "AppConfiguration", FormMethod.Post, new { @class = "form-horizontal" }))
    {   
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(x => x.Id)
        <div class="form-group">
            @Html.EditorFor(x => x.ApplicationName, new { ReadOnly = true })
        </div>
        <div class="form-group">
            @Html.EditorFor(x => x.Name, new { ReadOnly = true })
        </div>
        <div class="form-group">
            @Html.EditorFor(x => x.Value)
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
	            <input type="submit" value="@MUI.ButtonSave" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $('.rsa-form-group > div.col-sm-4').removeClass('col-sm-4').addClass('col-sm-7');
    $('.rsa-form-group > div.col-sm-2').removeClass('col-sm-2').addClass('col-sm-4');
    $('.modal-content').attr('style', 'width:740px;');
   
    
</script>