Downloads/cec.srv_indrivo-dev/src/CEC.SAISE.EDayModule/Controllers/VoterCertificatController.cs
using Amdaris;
using Amdaris.NHibernateProvider.Web;
using AutoMapper;
using CEC.SAISE.BLL;
using CEC.SAISE.BLL.Dto;
using CEC.SAISE.BLL.Helpers;
using CEC.SAISE.Domain;
using CEC.SAISE.EDayModule.Infrastructure;
using CEC.SAISE.EDayModule.Infrastructure.Grids;
using CEC.SAISE.EDayModule.Infrastructure.Security;
using CEC.SAISE.EDayModule.Models.VoterCertificate;
using Lib.Web.Mvc.JQuery.JqGrid;
using NHibernate;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CEC.SAISE.EDayModule.Controllers
{

    [NHibernateSession]
    [PermissionRequired(SaisePermissions.VoterCertificateCreate)]
    public class VoterCertificatController : BaseController
    {
        private readonly IConfigurationBll _configurationBll;
        private readonly IUserBll _userBll;
        private readonly IVotingBll _votingBll;
        private readonly ILogger _logger;
        private readonly ISaiseRepository _saiseRepository;
        private readonly IVoterCertificatBll _voterCertificatBll;

        public VoterCertificatController(IConfigurationBll configurationBll, IUserBll userBll, ILogger logger, ISessionFactory sessionFactory, ISaiseRepository saiseRepository, IVoterCertificatBll voterCertificatBll, IVotingBll votinBll)
        {
            _configurationBll = configurationBll;
            _userBll = userBll;
            _logger = logger;
            _saiseRepository = saiseRepository;
            _voterCertificatBll = voterCertificatBll;
            _votingBll = votinBll;
        }

        // GET: VoterCertificat
        public async Task<ActionResult> Index()
        {
           

            if (User.IsInRole("Administrator"))
            {
                return View("NotImplementedForAdmin");
            }
            var userData = await _userBll.GetCurrentUserData();

            if(userData.CircumscriptionAcces)
            {
                return View("_NotImplementForUC");
            }

            return View();
        }


        public JqGridJsonResult GetAllCertificats(JqGridRequest request)
        {
            var pageRequest = request.ToPageRequest<VoterCertificateGridModel>();

            var userIsAdmin = User.IsInRole("Administrator");

            var certificats = _voterCertificatBll.GetVoterCertificat(pageRequest);

            return certificats.ToJqGridJsonResult<VoterCertificatDto, VoterCertificateGridModel>();

        }


        public JqGridJsonResult SearchVoterAsync(JqGridRequest request, string idnp)
        {
            var pageRequest = request.ToPageRequest<VoterGridViewModel>();

            if (!string.IsNullOrWhiteSpace(idnp))
            {
                var searchResult = _voterCertificatBll.GetVoter(pageRequest, idnp);
                return searchResult.ToJqGridJsonResult<AssignedVoter, VoterGridViewModel>();
            }

            return null;
        }

        [HttpGet]
        public  ActionResult CreateCertifcat(string idnp)
        {
            var Election = _voterCertificatBll.GetDateOfElection();

            var trustPersone = _votingBll.SearchVoterAsync(idnp,"");

            var person = _voterCertificatBll.GetForCreateCertificat(trustPersone.Result.VoterData.Assignement.AssignedVoterId);



            string adress = person.AssignedVoter.Voter.GetAddress();



            if (trustPersone.Result.Status == VoterSearchStatus.Success && trustPersone.Result.VoterData.Assignement.IsSamePollingStation == true)
            {


                var result = new CertificatModel
                {
                    VoterSearchStatus = 1,
                    FullName = trustPersone.Result.VoterData.FirstName + " " + trustPersone.Result.VoterData.LastName,
                    Adres = person.AssignedVoter.Voter.Region.RegionType.Name+ person.AssignedVoter.Voter.Region.Name+ " " + adress,
                    BirthDate = person.AssignedVoter.Voter.DateOfBirth,
                    ElectionDate = Election.Result.ElectionDayDate.DateTime,
                    IDNP = trustPersone.Result.VoterData.Idnp,
                    DocumentNumber = trustPersone.Result.VoterData.DocumentNumber,
                    TypeElection =Election.Result.Name,
                    DocumentData = person.AssignedVoter.Voter.DateOfIssue,
                    DocumentExpireData = person.AssignedVoter.Voter.DateOfExpiry,
                    Circumscription = trustPersone.Result.VoterData.Assignement.Circumscription.Name,
                    ElectionOffice = trustPersone.Result.VoterData.Assignement.PollingStation.Name,
                    AssignedVoterId = trustPersone.Result.VoterData.Assignement.AssignedVoterId,
                    PolingStationId = trustPersone.Result.VoterData.Assignement.PollingStation.Id,
                    VoterId = trustPersone.Result.VoterData.VoterId
                    

                };
                return PartialView(result);
            }
            else if (trustPersone.Result.Status == VoterSearchStatus.Success && trustPersone.Result.VoterData.Assignement.IsSamePollingStation == false)
            {
                var result = new CertificatModel
                {
                    VoterSearchStatus = 2,

                    FullName = trustPersone.Result.VoterData.FirstName + " " + trustPersone.Result.VoterData.LastName,
                    TypeElection = "",
                    Circumscription = trustPersone.Result.VoterData.Assignement.Region.Name,
                    ElectionOffice = trustPersone.Result.VoterData.Assignement.PollingStation.Name
                };
                return PartialView(result);
            }
            else
            {
                var result = new CertificatModel
                {
                    VoterSearchStatus = 3
                };
                return PartialView(result);
            }

        }


        public ActionResult SelectVoterStatus()
        {
            var voterStatus = _saiseRepository.Query<PollingStation>();

            return PartialView("_Select", voterStatus.ToSelectListUnencrypted(0, false, null, x => x.FullName, x => x.Id));
        }


        [HttpPost]
        public ActionResult CreateCertifcat(CertificatModel model)
        {
            if (ModelState.IsValid)
            {

                var result = _voterCertificatBll.SaveCertificatAsync(Convert.ToInt64(model.Id),Convert.ToInt64(model.AssignedVoterId), model.CertificatNr, Convert.ToInt64(model.PolingStationId), model.ReleaseDate);

                if (result.Result)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }

            return PartialView(model);
        }



        [HttpGet]
        public ActionResult ViewCertificat(long id)
        {
            if (id != null)
            {
                var Certificat = _voterCertificatBll.GetCertificat(id);

                var CertifactModel = Mapper.Map<CertificatModel>(Certificat);
                return PartialView(CertifactModel);
            }

            return Content("Sa produs o eroare");
        }

        [HttpPost]
        public ActionResult ViewCertificat(CertificatModel model)
        {

            if (ModelState.IsValid)
            {
                var result = _voterCertificatBll.SaveCertificatAsync(Convert.ToInt64(model.Id), Convert.ToInt64(model.AssignedVoterId), model.CertificatNr, Convert.ToInt64(model.PolingStationId), model.ReleaseDate);

                if (result.Result)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }

            return PartialView(model);

        }

        public JsonResult DeleteCertificat(long id)
        {

            if (id != null)
            {
                var deleteCertificat = _voterCertificatBll.DeleteCerificat(id);
                return Json(deleteCertificat.Result, JsonRequestBehavior.AllowGet);
            }

            return Json(false, JsonRequestBehavior.AllowGet);



        }

    }
}

Downloads/cec.srv_indrivo-dev/src/CEC.SAISE.EDayModule/Views/VoterCertificat/CreateCertifcat.cshtml
@model CEC.SAISE.EDayModule.Models.VoterCertificate.CertificatModel
@using CEC.SAISE.BLL.Dto

@if (Model.VoterSearchStatus == 1)
{
    using (Html.BeginForm("CreateCertifcat", "VoterCertificat", FormMethod.Post, new { @class = "form-horizontal", autocomplete = "off", id = "certificatForm" }))
    {


        @Html.ValidationSummary(true)
        @Html.HiddenFor(x=>x.VoterSearchStatus)
        @Html.HiddenFor(x => x.PolingStationId)
        @Html.HiddenFor(x => x.VoterId)
        @Html.HiddenFor(x => x.AssignedVoterId)
        @Html.HiddenFor(x => x.ElectionId)
        @Html.HiddenFor(x=>x.ElectionDate)
        <div class="box-content">
            <h4 class="page-header"><strong>Datele Personale</strong></h4>
            <div class="row form-group">
                <div class="control-label col-sm-2">
                    <label>Numele Complet</label>
                </div>
                @Html.EditorFor(x => x.FullName, new { HideLabel = true, ReadOnly = true })
                <div class="control-label col-sm-2">
                    <label>Ziua Nasterii</label>
                </div>
                @Html.EditorFor(x => x.BirthDate, new { HideLabel = true, ReadOnly = true })
            </div>
            <div class="row form-group">
                <div class="control-label col-sm-2">
                    <label>IDNP</label>
                </div>
                @Html.EditorFor(x => x.IDNP, new { HideLabel = true, ReadOnly = true })
                <div class="control-label col-sm-2">
                    <label>Buletin de identitate</label>
                </div>
                @Html.EditorFor(x => x.DocumentNumber, new { HideLabel = true, ReadOnly = true })
            </div>
            <div class="row form-group">
                <div class="control-label col-sm-2">
                    <label>Data eliberării</label>
                </div>
                @Html.EditorFor(x => x.DocumentData, new { HideLabel = true, ReadOnly = true })
                <div class="control-label col-sm-2">
                    <label>Oficiul</label>
                </div>
                @Html.EditorFor(x => x.Office, new { HideLabel = true, ReadOnly = true })
            </div>
            <div class="row form-group">
                <div class="control-label col-sm-2">
                    <label>Valabil pînă la</label>
                </div>
                @Html.EditorFor(x => x.DocumentExpireData, new { HideLabel = true, ReadOnly = true })
            </div>

        </div>


        <div class="box-content" style="">
            <h4 class="page-header"><strong>Viza de reședință</strong></h4>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Adresa</label>
                </div>
                @Html.EditorFor(x => x.Adres, new { HideLabel = true, ReadOnly = true })
            </div>
        </div>



        <div class="box-content">
            <h4 class="page-header"><strong>Date privind eliberarea certificatului cu drept de vot </strong></h4>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Scrutin</label>
                </div>
                @Html.EditorFor(x => x.TypeElection, new { HideLabel = true, ReadOnly = true })
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Cicumscripția</label>
                </div>
                @Html.EditorFor(x => x.Circumscription, new { HideLabel = true, ReadOnly = true })
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Secția de votare</label>
                </div>
                
                @Html.EditorFor(x => x.ElectionOffice, new { HideLabel = true, ReadOnly = true })
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Data eliberării</label>
                </div>
                @Html.EditorFor(x => x.ReleaseDate, new { HideLabel = true })
               
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Numărul Certificat</label>
                </div>
                @Html.EditorFor(x => x.CertificatNr, new { HideLabel = true })
               
            </div>
        </div> 
    }
}

@if (Model.VoterSearchStatus == 2)
{
   
    <div class="box-content" id="box2" >
        <h4 class="page-header"><strong>Rezultatul cautarii pentru Domnul / Doamna @Model.FullName </strong> </h4>

        <h5 class="page-header">Certificatul cu drept de vot  poate fi eliberat doar la  : </h5>

        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Cicumscripția</label>
            </div>
            @Html.EditorFor(x => x.Circumscription, new { HideLabel = true, ReadOnly = true })
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Secția de votare</label>
            </div>
            @Html.EditorFor(x => x.ElectionOffice, new { HideLabel = true, ReadOnly = true })
        </div>
    </div>
    
            }

            @if (Model.VoterSearchStatus == 3)
            {
                <div class="box" id="box3" >
                    <div class="box-content">                        
                        <div class="form-group">
                            <div class="control-label">
                                <label>Căutare eșuată , persoana dată nu are virsta de 18 sau nu este nici intr-o lista de votare. </label>
                            </div>


                        </div>
                    </div>
                </div>
            }

            <style>
                .modal-dialog {
                    width: auto;
                    padding: 19px;
                }

                .bootstrap-dialog-title {
                    color: white;
                }
                
            </style>

<script>
    $(document).ready(function() {
        var date_input = $('input[name="ReleaseDate"]'); //our date input has the name "date"
        var container = $('.bootstrap-iso form').length > 0 ? $('.bootstrap-iso form').parent() : "body";
        var options = {
            dateFormat: 'dd.mm.yy',
            container: container,
            todayHighlight: true,
            autoclose: true,
            language: 'ro'

        };
        date_input.datepicker(options);

        var $button = document.getElementById("box2");
        if ($button != null) {
            window.disablesaveButton.call();
        }
        
    })
    
    
</script>

Downloads/cec.srv_indrivo-dev/src/CEC.SAISE.EDayModule/Views/VoterCertificat/Index.cshtml
@using CEC.SAISE.EDayModule.Infrastructure.Grids
@using CEC.SAISE.EDayModule.Models.VoterCertificate
@using Lib.Web.Mvc.JQuery.JqGrid
@using CEC.SAISE.EDayModule.Models.Voting

@Scripts.Render("~/bundles/jqGrid")

@{
    var grid = Html.GridOptions<VoterCertificateGridModel>("votingStats", rowsPerPage: 100)
         .SetOptions(x => x.MultiSelect = false)
        .BuildGrid(Url.Action("GetAllCertificats", "VoterCertificat"), exportAction: "PopulateTable1", columnChooser: true)
        .Navigator(new JqGridNavigatorOptions()
        {
            Add = false,
            Edit = true,
            Delete = true,
            CloneToTop = true,
            EditFunction = "$.CertificatView",
            DeleteFunction = "$.DeleteCertificat",

        })
        .AddNavigatorButton("Editează certificat", onClick: "$.CertificatView");

}



<div>

    @Html.Partial("_SearchVoter")
    <div id="wait" class="loader" style="display: block;  position: absolute; top: 100%; left: 40%; padding: 2px;"></div>
</div>


<div class="well">
    <div class="row">
        <div class="col-xs-12">
            @grid.GetHtml()
        </div>
    </div>
</div>


<script type="text/javascript">

    //$(window).resize(function () {
    //    if ($(window).width() < 960) {
    //        $("#votingStats").setGridParam({ AutoWidth: false }).trigger("reloadGrid");
    //        $("#votingStats").setGridParam({ width: 960 }).trigger("reloadGrid");
    //    }
    //    else {
          
    //        $("#votingStats").setGridParam({ AutoWidth: true }).trigger("reloadGrid");
    //    }
    //});
        $(document).ready(function () {
        @grid.GetJavaScript();



                var dateFormat = 'dd.mm.yy';
                  $.validator.addMethod('date', function (value, element) {
                    if (this.optional(element)) {
                        return true;
                    }

                    try {
                        $.datepicker.parseDate(dateFormat, value);
                    } catch (err) {
                        return false;
                    }
                    return true;
            });
              $(".datefield").datepicker({ dateFormat: dateFormat, changeYear: true });
              $("#ReleaseDate").datepicker({ dateFormat: dateFormat, changeYear: true });
              $("#gs_Created").datepicker({ dateFormat: dateFormat, changeYear: true });
              $("#gs_Election").datepicker({ dateFormat: dateFormat, changeYear: true });
              $("#gs_ReleaseDate").datepicker({ dateFormat: dateFormat, changeYear: true });

    });

    $.CertificatView = function (e) {
        var message = $('<div class="popupWindows"><div/>');

          var rowId = $("#votingStats").jqGrid('getGridParam', 'selrow');
          var rowData = jQuery("#votingStats").getRowData(rowId);
          var colData = rowData['CerificatID'];

          if (rowId == null || rowId.length == 0) {
            BootstrapDialog.alert({ message: 'Selectati rindul ', title: 'Eroare' });
            return;
          }

         var url = '@Url.Action("ViewCertificat", "VoterCertificat")';
         var dialogTitle = 'Editare  Certificat';
         var adres = url + '?id=' + colData;

         $.ajax({
             url: adres,
             type: 'GET',
             success: function (content) {
                 message.append(content);
                 var dialog = new BootstrapDialog({
                     title: dialogTitle,
                     message: message,
                     buttons: [
                         {
                             id:'EditCert',
                             label: 'Salveaza',
                             cssClass: 'btn btn-primary',
                             action: function (dialog) {
                                 var myForm = $('#certificatForm').serialize();
                                 $.ajax({
                                     type: "POST",
                                     url: url,
                                     data: myForm,
                                     success: function (result) {
                                         if (result == true) {
                                             dialog.getModalBody().html("Modificat cu succes .");
                                             $('#EditCert').attr("disabled", "disabled");
                                             return;
                                         }

                                         if (result == false) {
                                             dialog.getModalBody().html("Eronat mai incearcă");
                                             $('#EditCert').attr("disabled", "disabled");
                                             return;
                                         }

                                         dialog.getModalBody().html(result);


                                     }

                                 });

                             }
                         },
                         {
                             label: 'Închide',
                             action: function (dialog) {
                                 dialog.close();
                             }
                         }]
                 });
                 dialog.open();
             }
        });

    };




    $.DeleteCertificat = function (CerificatID) {

		var url = '@Url.Action("DeleteCertificat")';
        var message = 'Sunte-ți sigur ? ';
        BootstrapDialog.show({
            message: message,
            buttons: [
                {
                    label: 'Da',
                    action: function (dialogItself) {
                        $.ajax({
                            type: "POST",
                            url: url,
                            data: { id: CerificatID },
                            success: function () {
                                dialogItself.close();
                                $("#votingStats").trigger('reloadGrid');

                            }
                        });
                    }
                },
                {
                    label: 'Nu',
                    action: function (dialogItself) {
                        dialogItself.close();
                    }
                }
            ]
        });

    };


    $(document).ajaxStart(function () {
        $("#wait").css("display", "block");
    });
    $(document).ajaxComplete(function () {
        $("#wait").css("display", "none");
    });


</script>

Downloads/cec.srv_indrivo-dev/src/CEC.SAISE.EDayModule/Views/VoterCertificat/NotImplementedForAdmin.cshtml
<div class="well">
    <p class="lead">
        Ne cerem scuze, funcționalitatea nu este accesibila administratorilor.
    </p>
</div>

Downloads/cec.srv_indrivo-dev/src/CEC.SAISE.EDayModule/Views/VoterCertificat/ViewCertificat.cshtml
@model CEC.SAISE.EDayModule.Models.VoterCertificate.CertificatModel
@using CEC.SAISE.BLL.Dto


@using (Html.BeginForm("ViewCertificat", "VoterCertificat", FormMethod.Post, new { @class = "form-horizontal", autocomplete = "off" , id = "certificatForm" }))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(x => x.PolingStationId)
    @Html.HiddenFor(x => x.ElectionId)
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.ElectionId)
    @Html.HiddenFor(x => x.ElectionDate)
   
    <div class="box-content">
        <h4 class="page-header"><strong>Datele Personale</strong></h4>
        <div class="row form-group">
            <div class="control-label col-sm-2">
                <label>Numele Complet</label>
            </div>
            @Html.EditorFor(x => x.FullName, new { HideLabel = true, ReadOnly = true })
            <div class="control-label col-sm-2">
                <label>Ziua Nasterii</label>
            </div>
            @Html.EditorFor(x => x.BirthDate, new { HideLabel = true, ReadOnly = true })
        </div>
        <div class="row form-group">
            <div class="control-label col-sm-2">
                <label>IDNP</label>
            </div>
            @Html.EditorFor(x => x.IDNP, new { HideLabel = true, ReadOnly = true })
            <div class="control-label col-sm-2">
                <label>Buletin de identitate</label>
            </div>
            @Html.EditorFor(x => x.DocumentNumber, new { HideLabel = true, ReadOnly = true })
        </div>
        <div class="row form-group">
            <div class="control-label col-sm-2">
                <label>Data eliberării</label>
            </div>
            @Html.EditorFor(x => x.DocumentData, new { HideLabel = true, ReadOnly = true })
            <div class="control-label col-sm-2">
                <label>Oficiul</label>
            </div>
            @Html.EditorFor(x => x.Office, new { HideLabel = true, ReadOnly = true })
        </div>
        <div class="row form-group">
            <div class="control-label col-sm-2">
                <label>Valabil pînă la</label>
            </div>
            @Html.EditorFor(x => x.DocumentExpireData, new { HideLabel = true, ReadOnly = true })

        </div>

    </div>


    <div class="box-content" style="">
        <h4 class="page-header"><strong>Viza de reședință</strong></h4>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Adresa</label>
            </div>
            @Html.EditorFor(x => x.Adres, new { HideLabel = true, ReadOnly = true })
        </div>
    </div>



    <div class="box-content">
        <h4 class="page-header"><strong>Date privind eliberarea certificatului cu drept de vot </strong></h4>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Scrutin</label>
            </div>
            @Html.EditorFor(x => x.TypeElection, new { HideLabel = true, ReadOnly = true })
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Cicumscripția</label>
            </div>
            @Html.EditorFor(x => x.Circumscription, new { HideLabel = true, ReadOnly = true })
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Secția de votare</label>
            </div>
            @Html.EditorFor(x => x.ElectionOffice, new { HideLabel = true, ReadOnly = true })
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Data eliberării</label>
            </div>
            @Html.EditorFor(x => x.ReleaseDate, new { HideLabel = true })
            
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <label>Numărul Certificat</label>
            </div>
            @Html.EditorFor(x => x.CertificatNr, new { HideLabel = true,  })
          
        </div>         
    </div>

}




<style>
    .modal-dialog {
        width: 1000px !important;
        padding: 19px;
    }

    .bootstrap-dialog-title {
        color: white;
    }
</style>
<script>
    $(document).ready(function () {
        $('#buttonClose').on('click',
            function() {
                dialogItself.close();
                $('.close').click();
            });
    });
    $(document).ready(function () {
        var date_input = $('input[name="ReleaseDate"]'); //our date input has the name "date"
        var container = $('.bootstrap-iso form').length > 0 ? $('.bootstrap-iso form').parent() : "body";
        var options = {
            dateFormat: 'dd.mm.yy',
            container: container,
            todayHighlight: true,
            autoclose: true,
            language: 'es',

        };
        date_input.datepicker(options);

    })
</script>

Downloads/cec.srv_indrivo-dev/src/CEC.SAISE.EDayModule/Views/VoterCertificat/_NotImplementForUC.cshtml
<div class="well">
    <p class="lead">
        Ne cerem scuze, funcționalitatea nu este accesibilă pentru utilizator cu drept de acces per Circumsripție.
    </p>
</div>